import { useState } from "react";
import { KeyRound, X } from "lucide-react";
import { apiFetch } from "../lib/api";

export default function ChangePasswordControl({ className }: { className?: string }) {
  const [open, setOpen] = useState(false); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const close = () => { if (!saving) { setOpen(false); setMessage(""); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); if (newPassword !== confirmPassword) { setMessage("New password and confirmation do not match."); return; } setSaving(true); try { const response = await apiFetch("/api/auth/change-password", { method: "POST", body: JSON.stringify({ currentPassword, newPassword }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to change password."); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setMessage("Password changed successfully. Your old password no longer works."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to change password."); } finally { setSaving(false); } };
  return <><button type="button" onClick={() => setOpen(true)} className={className ?? "fixed bottom-5 right-5 z-40 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3 py-2 text-xs font-semibold text-white shadow-lg shadow-indigo-500/30 transition hover:bg-indigo-700"}><KeyRound size={15}/>Change password</button>{open && <div className="fixed inset-0 z-[70] flex items-center justify-center p-4"><button type="button" aria-label="Close change password" onClick={close} className="absolute inset-0 bg-slate-950/50 backdrop-blur-sm"/><form onSubmit={submit} className="relative w-full max-w-md rounded-2xl bg-white p-6 text-slate-900 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-bold">Change password</h2><p className="mt-1 text-sm text-slate-500">Confirm your current password to continue.</p></div><button type="button" onClick={close} className="rounded-lg p-1 text-slate-400 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-950/30 transition-colors"><X size={18}/></button></div><div className="space-y-3"><input required minLength={8} type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} placeholder="Current password" className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-indigo-500"/><input required minLength={8} type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} placeholder="New password (minimum 8 characters)" className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-indigo-500"/><input required minLength={8} type="password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} placeholder="Confirm new password" className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-indigo-500"/>{message && <p className={`rounded-xl px-3 py-2 text-sm ${message.startsWith("Password changed") ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-600"}`}>{message}</p>}<button disabled={saving} className="h-11 w-full rounded-xl bg-indigo-600 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Saving…" : "Save new password"}</button></div></form></div>}</>;
}
